In [1]:
import numpy as np

#Arrays

In [2]:
a = np.array([1, 2, 3, 4]) 
a

array([1, 2, 3, 4])

In [3]:
len(a) #número de dados ou de colunas na lista

4

In [4]:
b = np.array([[1, 2], [3, 4]]) 
b

array([[1, 2],
       [3, 4]])

In [5]:
len(b)

2

In [6]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Arange: cria uma lista, definindo início, fim e espaço entre os valores 

- a = número de partida
- b = número de parada (NÃO ENTRA na lista)
- c = tamanho dos passos para ir de a até b

In [7]:
np.arange(10) #lista de 0 a 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2, 10) #lista de 2 a 10

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 3, 0.1) #lista de 2 a 3, indo de 0.1 em 0.1

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

## Linspace: cria uma lista, definindo início, fim e quantidade de números, equidistantes 

- a = número de partida
- b = número de parada (ENTRA na lista)
- c = qtd. de números entre a e b

In [10]:
np.linspace(1., 4., 6) #lista de 6 valores equidistantes entre 1 e 4

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

## Eye: matriz identidade

np.eye(a,b)

- a = linhas
- b = colunas

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

## Diag

- irá criar uma matriz apenas com valores na diagonal principal
                 
- também retorna uma array 1D, caso duas arrays sejam fornecidas, formada apenas pelos elementos da diag. p.

In [13]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
np.diag(a)

array([1, 4])

## **Zeros**: cria uma array apenas com valor 0

zeros((a,b,c)) 

- a = linhas
- b = colunas 
- c = números de matrizes axb

In [16]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

## **Ones** : cria uma array apenas com valor 1

ones((a,b,c)) 

- a = linhas
- b = colunas 
- c = números de matrizes axb

In [18]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#**Replicando, adicionando ou alterando a lista**

In [20]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2] #cria uma lista contendo os dois primeiros itens de a
b += 1 #adiciona esses valores a lista a, somando 1 em cada

a,b

(array([2, 3, 3, 4, 5, 6]), array([2, 3]))

#**Indexação**

In [21]:
x = np.arange(10) #np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[2] # ([0],[1],[2]...)

2

In [22]:
x[-2] #penúltimo item 

8

In [23]:
x.shape = (2, 5) #rearranjo da dimensão de x
x  

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
x[1, 3] #procurando linha [1] e coluna [3]
#x[1][3] também pode ser comandado assim

8

In [25]:
x[1, -1] #procurando linha [1] e coluna [-1] (última)
#x[1][-1] também pode ser comandado assim

9

In [26]:
x[0] #toda a linha [0]

array([0, 1, 2, 3, 4])

In [27]:
x[:,0] #toda a coluna [0]

array([0, 5])

#**Fatiando e caminhando**

###$x[i:j:k] $

####- i = partida
####- j = parada (NÃO ENTRA)
####- k = passo

In [28]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2] 

array([1, 3, 5])

In [29]:
x[-2:10]

array([8, 9])

In [30]:
x[-3:3:-1] # passos inversos de 1 em 1

array([7, 6, 5, 4])

In [31]:
x[5:] #todos os itens de [5] em diante

array([5, 6, 7, 8, 9])

In [32]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]], ])
x.shape # 2 listas de 3 linhas e 1 coluna

(2, 3, 1)

In [33]:
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [34]:
x[1:2] #elemento entre linhas [1] e [2]

array([[[4],
        [5],
        [6]]])

In [35]:
x = np.arange(10, 1, -1) #criando lista de 10 a 1 (não entra) com "passos negativos"
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [36]:
x[np.array([3, 3, 1, 8])] #extraindo itens da lista x, respeitando o índice

array([7, 7, 9, 2])

In [37]:
x[np.array([3, 3, -3, 8])] 

array([7, 7, 4, 2])

#**Multiplicação vetorial  e escalar**  

In [38]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [39]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

#**Soma vetorial e de itens**

In [40]:
np.array([0,2,3,4]) + np.array([1,1,-1,2])

array([1, 3, 2, 6])

In [41]:
np.sum(x) # soma todos os itens da lista

54

#**Inserindo dados**

In [42]:
x = np.linspace(1,5,5)
x

array([1., 2., 3., 4., 5.])

In [43]:
np.append(x,10) #adiciona um valor no último índice

array([ 1.,  2.,  3.,  4.,  5., 10.])

In [44]:
np.insert(x,3,1) #substitui um valor no índice indicado

array([1., 2., 3., 1., 4., 5.])

In [45]:
np.delete(x,1) #deleta um valor do índice indicado

array([1., 3., 4., 5.])

#**Funções matemáticas**

In [46]:
np.sum

<function numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [47]:
np.sqrt(2) #raíz quadrada 

1.4142135623730951

In [48]:
np.cbrt(8) #raíz cúbica

2.0

In [49]:
np.e #n° de euler

2.718281828459045

In [50]:
np.log(2) #logarítmo natural

0.6931471805599453

In [51]:
np.log10(2) #logarítimo com base 10

0.3010299956639812

In [52]:
np.pi # pi

3.141592653589793

In [53]:
np.sin(np.pi/2) #em radianos 

1.0

In [54]:
np.sin(90*np.pi/180) #em graus 

1.0

In [55]:
np.cos(np.pi)

-1.0

In [56]:
np.tan(45*np.pi/180)

0.9999999999999999