___

<a href='https://sites.google.com/fat.uerj.br/livia'> <img src='../figures/capa2.png' /></a>
___

# Indexação e Seleção no NumPy (Indexing e Slicing)

Nesta seção vamos discutir como selecionar elementos ou grupos de elementos de um array.

In [2]:
import numpy as np

In [3]:
#Criando um array qualquer
arr = np.arange(0,11)

In [4]:
#Exibir
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexação e seleção usando colchetes (Brackets)
A maneira mais simples de escolher um ou alguns elementos de um array é muito semelhante às listas do python:

Pegar um elemento em uma indice

In [5]:

arr[8]

8

Pegar os elementos em um intervalo de indices

In [6]:

arr[1:5]

array([1, 2, 3, 4])

## Broadcasting

Os arrays do Numpy diferem de uma lista normal do Python por causa da sua capacidade de Broadcasting:

In [8]:
#Definir um valor com intervalo de índice (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
# Resetar array, Vamos ver porque precisamos resetar em breve
arr = np.arange(0,11)

#Exibir
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Uma nota importante sobre seleção
slice_of_arr = arr[0:6]

#Exibir slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
#Change Slice
slice_of_arr[:]=99

#Exibir o slice
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Agora observe que as mudanças também ocorrem em nosso array original!

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Os dados não são copiados, é uma visão (view) do array original! Isso evita problemas de memória!

In [13]:
#Para copiar um array temos que ser explicito
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexando um array 2D (matrizes)

O formato geral é **arr_2d[row][col]** ou **arr_2d[row,col]**. Eu recomendo geralmente usar a notação de vírgula para maior clareza.

In [14]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
#Indexing a linha
arr_2d[1]


array([20, 25, 30])

In [16]:
# Pegando o valor de um elemento
arr_2d[1][0]

20

In [17]:
# Pegando o valor de um elemento
arr_2d[1,0]

20

In [18]:
# slicing de um array 2D

#Shape(2,2) do canto superior direito
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
#Shape linha inferior
arr_2d[2]

array([35, 40, 45])

In [20]:
#Shape linha inferior
arr_2d[2,:]

array([35, 40, 45])

### Indexação sofisticada (Fancy Indexing)

A Fancy indexing permite que você selecione linhas ou colunas inteiras fora de ordem, para mostrar isso, vamos construir rapidamente um array:

In [21]:
#Criando o array 2D
arr2d = np.zeros((10,10))

In [22]:
#Comprimento de array
arr_length = arr2d.shape[1]

In [23]:
#Criando o array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Fancy indexing permite a seguinte operação

In [24]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [25]:
#Permite em qualquer ordem
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## Mais ajuda de indexação
Indexar um array 2D pode ser um pouco confuso no início, especialmente quando você começa a adicionar o tamanho do passo. Tente pesquisar imagens no google indexando NumPy para encontrar imagens úteis, como esta:

<img src= 'https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-020-2649-2/MediaObjects/41586_2020_2649_Fig1_HTML.png?as=webp' width=800/>

## Seleção

Vamos ver brevemente como usar colchetes (brackets) para seleção com base em operadores de comparação.

In [28]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [31]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Bom Trabalho!