___

<a href='https://sites.google.com/fat.uerj.br/livia'> <img src='../figures/capa2.png' /></a>
___

Aqui temos uma introdução rapida ao NumPy, que é uma biblioteca para computação científica em Python. A ideia é que vocês já tenham visto o básico de Python, e que estejam familiarizados com o uso de listas e dicionários. Se você não tem familiaridade com Python, recomendo que você veja o primeiro curso desta serie, que é uma introdução ao Python.

In [ ]:
!pip install numpy


In [1]:
import numpy as np

# Arrays

In [4]:
a = np.array([1., 2, 3, 4]) 
a

array([1., 2., 3., 4.])

In [5]:
a.dtype

dtype('float64')

In [6]:
len(a) #número de dados ou de colunas na lista

4

In [7]:
b = np.array([[1, 2], [3, 4]]) 
b

array([[1, 2],
       [3, 4]])

In [8]:
len(b)

2

In [9]:
b.shape

(2, 2)

In [11]:
type(b.shape)

tuple

In [10]:
b.shape[0]

2

In [12]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
c.shape

(2, 2, 2)

## Arange: cria uma lista, definindo início, fim e espaço entre os valores 

- a = número de partida
- b = número de parada (NÃO ENTRA na lista)
- c = tamanho dos passos para ir de a até b

In [17]:
np.arange(10) #lista de 0 a 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2, 10) #lista de 2 a 10

array([2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(2, 3, 0.1) #lista de 2 a 3, indo de 0.1 em 0.1

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

## Linspace: cria uma lista, definindo início, fim e quantidade de números, equidistantes 

- a = número de partida
- b = número de parada (ENTRA na lista)
- c = qtd. de números entre a e b

In [20]:
np.linspace(1., 4., 6) #lista de 6 valores equidistantes entre 1 e 4

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [21]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## Eye: matriz identidade

np.eye(a,b)

- a = linhas
- b = colunas

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

## Diag

- irá criar uma matriz apenas com valores na diagonal principal
                 
- também retorna uma array 1D, caso duas arrays sejam fornecidas, formada apenas pelos elementos da diag. p.

In [24]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [26]:
np.diag(a)

array([1, 4])

## **Zeros**: cria uma array apenas com valor 0

zeros((a,b,c)) 

- a = linhas
- b = colunas 
- c = números de matrizes axb

In [27]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

## **Ones** : cria uma array apenas com valor 1

ones((a,b,c)) 

- a = linhas
- b = colunas 
- c = números de matrizes axb

In [29]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

## Multiplicação Matricial

In [30]:
mat1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat2 = np.array(mat1)
np.dot(mat2, mat2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [31]:
mat3 = np.zeros([3, 3])
for i in range(3):
    for k in range(3):
        for j in range(3):
            mat3[i][k] = mat3[i][k] + mat1[i][j] * mat1[j][k]
mat3

array([[ 30.,  36.,  42.],
       [ 66.,  81.,  96.],
       [102., 126., 150.]])

## Comparação de tempo com o Python

In [32]:
import time
mat1 = np.random.rand(50, 50)
mat2 = np.array(mat1)
t = time.time()
mat3 = np.dot(mat2, mat2)
nptime = time.time() - t
mat3 = np.zeros([50, 50])
t = time.time()
for i in range(50):
    for k in range(50):
        for j in range(50):
            mat3[i][k] = mat3[i][k] + mat1[i][j] * mat1[j][k]
pytime = time.time() - t
times = str(pytime / nptime)
print("NumPy is " + times + " times faster!")

NumPy is 6.7073673777266 times faster!


## Arrays Booleano

In [34]:
l = [0, 1,2,3,4,5,6,7,8,9]
l < 5

TypeError: '<' not supported between instances of 'list' and 'int'

In [33]:
arr = np.array([0, 1,2,3,4,5,6,7,8,9])
bool_arr = (arr < 5)
bool_arr


array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [35]:
bool_arr1 = (arr == 0)
bool_arr1

array([ True, False, False, False, False, False, False, False, False,
       False])

## **Replicando, adicionando ou alterando a array**

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[0:2] #cria uma lista contendo os dois primeiros itens de a
b

array([1, 2])

In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[0:2] #cria uma lista contendo os dois primeiros itens de a
b = b + 1 #adiciona esses valores a lista a, somando 1 em cada (b+=1)

a,b

(array([1, 2, 3, 4, 5, 6]), array([2, 3]))

In [39]:
b.base

In [38]:
c = a[:2].copy()

# **Indexação**

In [51]:
x = np.arange(10) #np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[2] # ([0],[1],[2]...)

np.int64(2)

In [42]:
x[2] == 2.

np.True_

In [43]:
2 == 2

True

In [44]:
x[-2] #penúltimo item 

np.int64(8)

In [46]:
x.shape

(10,)

In [53]:
x.shape = (2, 5) #rearranjo da dimensão de x
x  

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
x = np.arange(10)
x.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
x[1, 3] #procurando linha [1] e coluna [3]
#x[1][3] também pode ser comandado assim

np.int64(8)

In [25]:
x[1, -1] #procurando linha [1] e coluna [-1] (última)
#x[1][-1] também pode ser comandado assim

9

In [56]:
x[0] #toda a linha [0]

array([0, 1, 2, 3, 4])

In [57]:
x[:,0] #toda a coluna [0]

array([0, 5])

Indexação com arrays Booleano

In [59]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:

y = arr % 2 == 0
y


array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [62]:
arr[y]

array([0, 2, 4, 6, 8])

Como fazer no python?

In [63]:
l = list(range(10))
pares = []

for item in l:
    if item % 2 == 0:
        pares.append(item)


print(pares)

[0, 2, 4, 6, 8]


## Procurar e Substituir valores em Arrays

In [65]:
a, b = arr.copy().reshape(2,5), arr.copy().reshape(2,5)

print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


colocar numero 5 onde tiver um numero par no array

In [67]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if a[i, j] % 2 == 0:
            a[i, j] = 5
a

array([[5, 1, 5, 3, 5],
       [5, 5, 7, 5, 9]])

In [68]:
b[b % 2 == 0] = 5
b


array([[5, 1, 5, 3, 5],
       [5, 5, 7, 5, 9]])

# **Fatiando e caminhando**

### $x[i:j:k] $

#### - i = partida
#### - j = parada (NÃO ENTRA)
#### - k = passo

In [69]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x[1:7:2] 

array([1, 3, 5])

In [72]:
x[-2:11]

array([8, 9])

In [73]:
x[-3:3:-1] # passos inversos de 1 em 1

array([7, 6, 5, 4])

In [74]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
x[5:] #todos os itens de [5] em diante

array([5, 6, 7, 8, 9])

In [32]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]], ])
x.shape # 2 listas de 3 linhas e 1 coluna

(2, 3, 1)

In [33]:
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [34]:
x[1:2] #elemento entre linhas [1] e [2]

array([[[4],
        [5],
        [6]]])

In [35]:
x = np.arange(10, 1, -1) #criando lista de 10 a 1 (não entra) com "passos negativos"
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [36]:
x[np.array([3, 3, 1, 8])] #extraindo itens da lista x, respeitando o índice

array([7, 7, 9, 2])

In [37]:
x[np.array([3, 3, -3, 8])] 

array([7, 7, 4, 2])

# **Multiplicação vetorial  e escalar**  

In [38]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [39]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b #broadcasting

array([2., 4., 6.])

# **Soma vetorial e de itens**

Em python

In [75]:
[0,2,3,4] + [1,1,-1,2]

[0, 2, 3, 4, 1, 1, -1, 2]

In [78]:
x = np.array([0,2,3,4]) + np.array([1,1,-1,2])

In [79]:
np.sum(x) # soma todos os itens da lista

np.int64(12)

In [80]:
x.sum()

np.int64(12)

In [81]:
x.mean()

np.float64(3.0)

# **Inserindo dados**

In [82]:
x = np.linspace(1,5,5)
x

array([1., 2., 3., 4., 5.])

In [85]:
# x.append(10) # não funciona igual ap Python

In [87]:
np.append(x,10) #adiciona um valor no último índice

array([ 1.,  2.,  3.,  4.,  5., 10.])

In [88]:
np.insert(x,3,1) #substitui um valor no índice indicado

array([1., 2., 3., 1., 4., 5.])

In [90]:
x

array([1., 2., 3., 4., 5.])

In [91]:
np.delete(x,1) #deleta um valor do índice indicado

array([1., 3., 4., 5.])

A operação não é `inplace` 

In [92]:
x

array([1., 2., 3., 4., 5.])

## Reshape

In [ ]:
arr = np.arange(15)
arr.reshape((3, 5))
arr

## Logica Condicional

In [93]:
a = np.array([4, 7, 5, -7, 9, 0])
b = np.array([-1, 9, 8, 3, 3, 3])
cond = np.array([True, True, False, True, False, False])
res = np.where(cond, a, b)
res

array([ 4,  7,  8, -7,  3,  3])

In [94]:
res = np.where(a <= b, b, a)
res

array([4, 9, 8, 3, 9, 3])

In [95]:
l = [1,2,3]
for idx, item in enumerate(l):
    print(idx, item)

0 1
1 2
2 3


In [102]:
res = []

for ind, item in enumerate(a):
    if item <= b[ind]:
        res.append(b[ind])
    else:
        res.append(item)
(res)

[np.int64(4), np.int64(9), np.int64(8), np.int64(3), np.int64(9), np.int64(3)]

In [103]:
print(arr)
res = np.where(arr < 5, 0, arr)
res

[0 1 2 3 4 5 6 7 8 9]


array([0, 0, 0, 0, 0, 5, 6, 7, 8, 9])

# **Funções matemáticas**

In [46]:
np.sum

<function numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [47]:
np.sqrt(2) #raíz quadrada 

1.4142135623730951

In [106]:
x

array([1., 2., 3., 4., 5.])

In [105]:
np.sqrt(x) #vetorização

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

A vetorização não exite na biblioteca `math`

In [107]:
import math

In [109]:
try:
    math.sqrt(x)
except Exception as e:
    print(e)

only length-1 arrays can be converted to Python scalars


In [48]:
np.cbrt(8) #raíz cúbica

2.0

In [110]:
np.e #n° de euler

2.718281828459045

In [111]:
np.log(2) #logarítmo natural

np.float64(0.6931471805599453)

In [116]:
float(np.log10(2)) #logarítimo com base 10

0.3010299956639812

In [117]:
np.pi # pi

3.141592653589793

In [118]:
np.sin(np.pi/2) #em radianos 

np.float64(1.0)

In [119]:
np.sin(90 ) #em graus 

np.float64(0.8939966636005579)

In [55]:
np.cos(np.pi)

-1.0

In [56]:
np.tan(45*np.pi/180)

0.9999999999999999

$$
2x+3y = 5\\
4x+y = 6
$$
​

​


In [120]:
import numpy as np

# Matriz de coeficientes
A = np.array([[2, 3], [4, 1]])

# Vetor de resultados
b = np.array([5, 6])

# Resolver o sistema
solution = np.linalg.solve(A, b)

# Exibir os resultados
print("Solução (x, y):", solution)


Solução (x, y): [1.3 0.8]
